---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: tenant1

scrape_configs:
  - job_name: flog_scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            # Note: quote "service.name" so the dot isn’t treated as nesting
            service_name: '"service.name"'
            trace_id: trace_id
            span_id: span_id
      - labels:
          service_name:
          trace_id:
          span_id:

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
